#!/usr/bin/env ansible-playbook -i inventory
---

- name: Provision the instances
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - include: tasks/keypair.yaml name="sitekey"
    - include: tasks/securitygroup.yaml name="webservers"
    - include: tasks/securitygroup.yaml name="dbservers"
    - include: tasks/instance.yaml name="web1" securitygroup="webservers" keypair="sitekey"
    - include: tasks/instance.yaml name="web2" securitygroup="webservers" keypair="sitekey"
    - include: tasks/instance.yaml name="db1" securitygroup="dbservers" keypair="sitekey"
    - include: tasks/instance.yaml name="db2" securitygroup="dbservers" keypair="sitekey"
