---

- name: Provision the instances
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - include: tasks/keypair.yaml name="site1key"
    - include: tasks/keypair.yaml name="site2key"
    - include: tasks/securitygroup.yaml name="webservers"
    - include: tasks/securitygroup.yaml name="dbservers"
    - include: tasks/instance.yaml name="web1" securitygroup="webservers" keypair="site1key"
    - include: tasks/instance.yaml name="web2" securitygroup="webservers" keypair="site2key"
    - include: tasks/instance.yaml name="db1" securitygroup="dbservers" keypair="site1key"
    - include: tasks/instance.yaml name="db2" securitygroup="dbservers" keypair="site2key"

