---

- name: Configure common packages
  hosts:
    - security_group_webservers
    - security_group_dbservers
  sudo: true
  ssh_user: ubuntu
  ansible_ssh_private_key_file: "keys/{{ ec2_key_name }}"
  roles:
    - ssh-reachable
    - ubuntu-updated
    - hostname-configured

- name: Configure webserver packages
  hosts: security_group_webservers
  sudo: true
  ssh_user: ubuntu
  ansible_ssh_private_key_file: "keys/{{ ec2_key_name }}"
  roles:
    - { role: nginx-server, header: "This is the {{ ec2_tag_Name }} server." }

